<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('kebangsaans')->delete();

        $countries = array(
            array('country_id' => '104', 'tiket_id' => '1', 'negara' => 'Indonesia', 'code' => 'ID'),
            array('country_id' => '1', 'tiket_id' => '2', 'negara' => 'Afghanistan', 'code' => 'AF'),
            array('country_id' => '2', 'tiket_id' => '2', 'negara' => 'Åland Islands', 'code' => 'AX'),
            array('country_id' => '3', 'tiket_id' => '2', 'negara' => 'Albania', 'code' => 'AL'),
            array('country_id' => '4', 'tiket_id' => '2', 'negara' => 'Algeria', 'code' => 'DZ'),
            array('country_id' => '5', 'tiket_id' => '2', 'negara' => 'American Samoa', 'code' => 'AS'),
            array('country_id' => '6', 'tiket_id' => '2', 'negara' => 'Andorra', 'code' => 'AD'),
            array('country_id' => '7', 'tiket_id' => '2', 'negara' => 'Angola', 'code' => 'AO'),
            array('country_id' => '8', 'tiket_id' => '2', 'negara' => 'Anguilla', 'code' => 'AI'),
            array('country_id' => '9', 'tiket_id' => '2', 'negara' => 'Antarctica', 'code' => 'AQ'),
            array('country_id' => '10', 'tiket_id' => '2', 'negara' => 'Antigua and Barbuda', 'code' => 'AG'),
            array('country_id' => '11', 'tiket_id' => '2', 'negara' => 'Argentina', 'code' => 'AR'),
            array('country_id' => '12', 'tiket_id' => '2', 'negara' => 'Armenia', 'code' => 'AM'),
            array('country_id' => '13', 'tiket_id' => '2', 'negara' => 'Aruba', 'code' => 'AW'),
            array('country_id' => '14', 'tiket_id' => '2', 'negara' => 'Australia', 'code' => 'AU'),
            array('country_id' => '15', 'tiket_id' => '2', 'negara' => 'Austria', 'code' => 'AT'),
            array('country_id' => '16', 'tiket_id' => '2', 'negara' => 'Azerbaijan', 'code' => 'AZ'),
            array('country_id' => '17', 'tiket_id' => '2', 'negara' => 'Bahamas', 'code' => 'BS'),
            array('country_id' => '18', 'tiket_id' => '2', 'negara' => 'Bahrain', 'code' => 'BH'),
            array('country_id' => '19', 'tiket_id' => '2', 'negara' => 'Bangladesh', 'code' => 'BD'),
            array('country_id' => '20', 'tiket_id' => '2', 'negara' => 'Barbados', 'code' => 'BB'),
            array('country_id' => '21', 'tiket_id' => '2', 'negara' => 'Belarus', 'code' => 'BY'),
            array('country_id' => '22', 'tiket_id' => '2', 'negara' => 'Belgium', 'code' => 'BE'),
            array('country_id' => '23', 'tiket_id' => '2', 'negara' => 'Belize', 'code' => 'BZ'),
            array('country_id' => '24', 'tiket_id' => '2', 'negara' => 'Benin', 'code' => 'BJ'),
            array('country_id' => '25', 'tiket_id' => '2', 'negara' => 'Bermuda', 'code' => 'BM'),
            array('country_id' => '26', 'tiket_id' => '2', 'negara' => 'Bhutan', 'code' => 'BT'),
            array('country_id' => '27', 'tiket_id' => '2', 'negara' => 'Bolivia, Plurinational State of', 'code' => 'BO'),
            array('country_id' => '28', 'tiket_id' => '2', 'negara' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ'),
            array('country_id' => '29', 'tiket_id' => '2', 'negara' => 'Bosnia and Herzegovina', 'code' => 'BA'),
            array('country_id' => '30', 'tiket_id' => '2', 'negara' => 'Botswana', 'code' => 'BW'),
            array('country_id' => '31', 'tiket_id' => '2', 'negara' => 'Bouvet Island', 'code' => 'BV'),
            array('country_id' => '32', 'tiket_id' => '2', 'negara' => 'Brazil', 'code' => 'BR'),
            array('country_id' => '33', 'tiket_id' => '2', 'negara' => 'British Indian Ocean Territory', 'code' => 'IO'),
            array('country_id' => '34', 'tiket_id' => '2', 'negara' => 'Brunei Darussalam', 'code' => 'BN'),
            array('country_id' => '35', 'tiket_id' => '2', 'negara' => 'Bulgaria', 'code' => 'BG'),
            array('country_id' => '36', 'tiket_id' => '2', 'negara' => 'Burkina Faso', 'code' => 'BF'),
            array('country_id' => '37', 'tiket_id' => '2', 'negara' => 'Burundi', 'code' => 'BI'),
            array('country_id' => '38', 'tiket_id' => '2', 'negara' => 'Cambodia', 'code' => 'KH'),
            array('country_id' => '39', 'tiket_id' => '2', 'negara' => 'Cameroon', 'code' => 'CM'),
            array('country_id' => '40', 'tiket_id' => '2', 'negara' => 'Canada', 'code' => 'CA'),
            array('country_id' => '41', 'tiket_id' => '2', 'negara' => 'Cape Verde', 'code' => 'CV'),
            array('country_id' => '42', 'tiket_id' => '2', 'negara' => 'Cayman Islands', 'code' => 'KY'),
            array('country_id' => '43', 'tiket_id' => '2', 'negara' => 'Central African Republic', 'code' => 'CF'),
            array('country_id' => '44', 'tiket_id' => '2', 'negara' => 'Chad', 'code' => 'TD'),
            array('country_id' => '45', 'tiket_id' => '2', 'negara' => 'Chile', 'code' => 'CL'),
            array('country_id' => '46', 'tiket_id' => '2', 'negara' => 'China', 'code' => 'CN'),
            array('country_id' => '47', 'tiket_id' => '2', 'negara' => 'Christmas Island', 'code' => 'CX'),
            array('country_id' => '48', 'tiket_id' => '2', 'negara' => 'Cocos (Keeling) Islands', 'code' => 'CC'),
            array('country_id' => '49', 'tiket_id' => '2', 'negara' => 'Colombia', 'code' => 'CO'),
            array('country_id' => '50', 'tiket_id' => '2', 'negara' => 'Comoros', 'code' => 'KM'),
            array('country_id' => '51', 'tiket_id' => '2', 'negara' => 'Congo', 'code' => 'CG'),
            array('country_id' => '52', 'tiket_id' => '2', 'negara' => 'Congo, the Democratic Republic of the', 'code' => 'CD'),
            array('country_id' => '53', 'tiket_id' => '2', 'negara' => 'Cook Islands', 'code' => 'CK'),
            array('country_id' => '54', 'tiket_id' => '2', 'negara' => 'Costa Rica', 'code' => 'CR'),
            array('country_id' => '55', 'tiket_id' => '2', 'negara' => 'Côte d\'Ivoire', 'code' => 'CI'),
            array('country_id' => '56', 'tiket_id' => '2', 'negara' => 'Croatia', 'code' => 'HR'),
            array('country_id' => '57', 'tiket_id' => '2', 'negara' => 'Cuba', 'code' => 'CU'),
            array('country_id' => '58', 'tiket_id' => '2', 'negara' => 'Curaçao', 'code' => 'CW'),
            array('country_id' => '59', 'tiket_id' => '2', 'negara' => 'Cyprus', 'code' => 'CY'),
            array('country_id' => '60', 'tiket_id' => '2', 'negara' => 'Czech Republic', 'code' => 'CZ'),
            array('country_id' => '61', 'tiket_id' => '2', 'negara' => 'Denmark', 'code' => 'DK'),
            array('country_id' => '62', 'tiket_id' => '2', 'negara' => 'Djibouti', 'code' => 'DJ'),
            array('country_id' => '63', 'tiket_id' => '2', 'negara' => 'Dominica', 'code' => 'DM'),
            array('country_id' => '64', 'tiket_id' => '2', 'negara' => 'Dominican Republic', 'code' => 'DO'),
            array('country_id' => '65', 'tiket_id' => '2', 'negara' => 'Ecuador', 'code' => 'EC'),
            array('country_id' => '66', 'tiket_id' => '2', 'negara' => 'Egypt', 'code' => 'EG'),
            array('country_id' => '67', 'tiket_id' => '2', 'negara' => 'El Salvador', 'code' => 'SV'),
            array('country_id' => '68', 'tiket_id' => '2', 'negara' => 'Equatorial Guinea', 'code' => 'GQ'),
            array('country_id' => '69', 'tiket_id' => '2', 'negara' => 'Eritrea', 'code' => 'ER'),
            array('country_id' => '70', 'tiket_id' => '2', 'negara' => 'Estonia', 'code' => 'EE'),
            array('country_id' => '71', 'tiket_id' => '2', 'negara' => 'Ethiopia', 'code' => 'ET'),
            array('country_id' => '72', 'tiket_id' => '2', 'negara' => 'Falkland Islands (Malvinas)', 'code' => 'FK'),
            array('country_id' => '73', 'tiket_id' => '2', 'negara' => 'Faroe Islands', 'code' => 'FO'),
            array('country_id' => '74', 'tiket_id' => '2', 'negara' => 'Fiji', 'code' => 'FJ'),
            array('country_id' => '75', 'tiket_id' => '2', 'negara' => 'Finland', 'code' => 'FI'),
            array('country_id' => '76', 'tiket_id' => '2', 'negara' => 'France', 'code' => 'FR'),
            array('country_id' => '77', 'tiket_id' => '2', 'negara' => 'French Guiana', 'code' => 'GF'),
            array('country_id' => '78', 'tiket_id' => '2', 'negara' => 'French Polynesia', 'code' => 'PF'),
            array('country_id' => '79', 'tiket_id' => '2', 'negara' => 'French Southern Territories', 'code' => 'TF'),
            array('country_id' => '80', 'tiket_id' => '2', 'negara' => 'Gabon', 'code' => 'GA'),
            array('country_id' => '81', 'tiket_id' => '2', 'negara' => 'Gambia', 'code' => 'GM'),
            array('country_id' => '82', 'tiket_id' => '2', 'negara' => 'Georgia', 'code' => 'GE'),
            array('country_id' => '83', 'tiket_id' => '2', 'negara' => 'Germany', 'code' => 'DE'),
            array('country_id' => '84', 'tiket_id' => '2', 'negara' => 'Ghana', 'code' => 'GH'),
            array('country_id' => '85', 'tiket_id' => '2', 'negara' => 'Gibraltar', 'code' => 'GI'),
            array('country_id' => '86', 'tiket_id' => '2', 'negara' => 'Greece', 'code' => 'GR'),
            array('country_id' => '87', 'tiket_id' => '2', 'negara' => 'Greenland', 'code' => 'GL'),
            array('country_id' => '88', 'tiket_id' => '2', 'negara' => 'Grenada', 'code' => 'GD'),
            array('country_id' => '89', 'tiket_id' => '2', 'negara' => 'Guadeloupe', 'code' => 'GP'),
            array('country_id' => '90', 'tiket_id' => '2', 'negara' => 'Guam', 'code' => 'GU'),
            array('country_id' => '91', 'tiket_id' => '2', 'negara' => 'Guatemala', 'code' => 'GT'),
            array('country_id' => '92', 'tiket_id' => '2', 'negara' => 'Guernsey', 'code' => 'GG'),
            array('country_id' => '93', 'tiket_id' => '2', 'negara' => 'Guinea', 'code' => 'GN'),
            array('country_id' => '94', 'tiket_id' => '2', 'negara' => 'Guinea-Bissau', 'code' => 'GW'),
            array('country_id' => '95', 'tiket_id' => '2', 'negara' => 'Guyana', 'code' => 'GY'),
            array('country_id' => '96', 'tiket_id' => '2', 'negara' => 'Haiti', 'code' => 'HT'),
            array('country_id' => '97', 'tiket_id' => '2', 'negara' => 'Heard Island and McDonald Mcdonald Islands', 'code' => 'HM'),
            array('country_id' => '98', 'tiket_id' => '2', 'negara' => 'Holy See (Vatican City State)', 'code' => 'VA'),
            array('country_id' => '99', 'tiket_id' => '2', 'negara' => 'Honduras', 'code' => 'HN'),
            array('country_id' => '100', 'tiket_id' => '2', 'negara' => 'Hong Kong', 'code' => 'HK'),
            array('country_id' => '101', 'tiket_id' => '2', 'negara' => 'Hungary', 'code' => 'HU'),
            array('country_id' => '102', 'tiket_id' => '2', 'negara' => 'Iceland', 'code' => 'IS'),
            array('country_id' => '103', 'tiket_id' => '2', 'negara' => 'India', 'code' => 'IN'),
            array('country_id' => '105', 'tiket_id' => '2', 'negara' => 'Iran, Islamic Republic of', 'code' => 'IR'),
            array('country_id' => '106', 'tiket_id' => '2', 'negara' => 'Iraq', 'code' => 'IQ'),
            array('country_id' => '107', 'tiket_id' => '2', 'negara' => 'Ireland', 'code' => 'IE'),
            array('country_id' => '108', 'tiket_id' => '2', 'negara' => 'Isle of Man', 'code' => 'IM'),
            array('country_id' => '109', 'tiket_id' => '2', 'negara' => 'Israel', 'code' => 'IL'),
            array('country_id' => '110', 'tiket_id' => '2', 'negara' => 'Italy', 'code' => 'IT'),
            array('country_id' => '111', 'tiket_id' => '2', 'negara' => 'Jamaica', 'code' => 'JM'),
            array('country_id' => '112', 'tiket_id' => '2', 'negara' => 'Japan', 'code' => 'JP'),
            array('country_id' => '113', 'tiket_id' => '2', 'negara' => 'Jersey', 'code' => 'JE'),
            array('country_id' => '114', 'tiket_id' => '2', 'negara' => 'Jordan', 'code' => 'JO'),
            array('country_id' => '115', 'tiket_id' => '2', 'negara' => 'Kazakhstan', 'code' => 'KZ'),
            array('country_id' => '116', 'tiket_id' => '2', 'negara' => 'Kenya', 'code' => 'KE'),
            array('country_id' => '117', 'tiket_id' => '2', 'negara' => 'Kiribati', 'code' => 'KI'),
            array('country_id' => '118', 'tiket_id' => '2', 'negara' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP'),
            array('country_id' => '119', 'tiket_id' => '2', 'negara' => 'Korea, Republic of', 'code' => 'KR'),
            array('country_id' => '120', 'tiket_id' => '2', 'negara' => 'Kuwait', 'code' => 'KW'),
            array('country_id' => '121', 'tiket_id' => '2', 'negara' => 'Kyrgyzstan', 'code' => 'KG'),
            array('country_id' => '122', 'tiket_id' => '2', 'negara' => 'Lao People\'s Democratic Republic', 'code' => 'LA'),
            array('country_id' => '123', 'tiket_id' => '2', 'negara' => 'Latvia', 'code' => 'LV'),
            array('country_id' => '124', 'tiket_id' => '2', 'negara' => 'Lebanon', 'code' => 'LB'),
            array('country_id' => '125', 'tiket_id' => '2', 'negara' => 'Lesotho', 'code' => 'LS'),
            array('country_id' => '126', 'tiket_id' => '2', 'negara' => 'Liberia', 'code' => 'LR'),
            array('country_id' => '127', 'tiket_id' => '2', 'negara' => 'Libya', 'code' => 'LY'),
            array('country_id' => '128', 'tiket_id' => '2', 'negara' => 'Liechtenstein', 'code' => 'LI'),
            array('country_id' => '129', 'tiket_id' => '2', 'negara' => 'Lithuania', 'code' => 'LT'),
            array('country_id' => '130', 'tiket_id' => '2', 'negara' => 'Luxembourg', 'code' => 'LU'),
            array('country_id' => '131', 'tiket_id' => '2', 'negara' => 'Macao', 'code' => 'MO'),
            array('country_id' => '132', 'tiket_id' => '2', 'negara' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MK'),
            array('country_id' => '133', 'tiket_id' => '2', 'negara' => 'Madagascar', 'code' => 'MG'),
            array('country_id' => '134', 'tiket_id' => '2', 'negara' => 'Malawi', 'code' => 'MW'),
            array('country_id' => '135', 'tiket_id' => '2', 'negara' => 'Malaysia', 'code' => 'MY'),
            array('country_id' => '136', 'tiket_id' => '2', 'negara' => 'Maldives', 'code' => 'MV'),
            array('country_id' => '137', 'tiket_id' => '2', 'negara' => 'Mali', 'code' => 'ML'),
            array('country_id' => '138', 'tiket_id' => '2', 'negara' => 'Malta', 'code' => 'MT'),
            array('country_id' => '139', 'tiket_id' => '2', 'negara' => 'Marshall Islands', 'code' => 'MH'),
            array('country_id' => '140', 'tiket_id' => '2', 'negara' => 'Martinique', 'code' => 'MQ'),
            array('country_id' => '141', 'tiket_id' => '2', 'negara' => 'Mauritania', 'code' => 'MR'),
            array('country_id' => '142', 'tiket_id' => '2', 'negara' => 'Mauritius', 'code' => 'MU'),
            array('country_id' => '143', 'tiket_id' => '2', 'negara' => 'Mayotte', 'code' => 'YT'),
            array('country_id' => '144', 'tiket_id' => '2', 'negara' => 'Mexico', 'code' => 'MX'),
            array('country_id' => '145', 'tiket_id' => '2', 'negara' => 'Micronesia, Federated States of', 'code' => 'FM'),
            array('country_id' => '146', 'tiket_id' => '2', 'negara' => 'Moldova, Republic of', 'code' => 'MD'),
            array('country_id' => '147', 'tiket_id' => '2', 'negara' => 'Monaco', 'code' => 'MC'),
            array('country_id' => '148', 'tiket_id' => '2', 'negara' => 'Mongolia', 'code' => 'MN'),
            array('country_id' => '149', 'tiket_id' => '2', 'negara' => 'Montenegro', 'code' => 'ME'),
            array('country_id' => '150', 'tiket_id' => '2', 'negara' => 'Montserrat', 'code' => 'MS'),
            array('country_id' => '151', 'tiket_id' => '2', 'negara' => 'Morocco', 'code' => 'MA'),
            array('country_id' => '152', 'tiket_id' => '2', 'negara' => 'Mozambique', 'code' => 'MZ'),
            array('country_id' => '153', 'tiket_id' => '2', 'negara' => 'Myanmar', 'code' => 'MM'),
            array('country_id' => '154', 'tiket_id' => '2', 'negara' => 'Namibia', 'code' => 'NA'),
            array('country_id' => '155', 'tiket_id' => '2', 'negara' => 'Nauru', 'code' => 'NR'),
            array('country_id' => '156', 'tiket_id' => '2', 'negara' => 'Nepal', 'code' => 'NP'),
            array('country_id' => '157', 'tiket_id' => '2', 'negara' => 'Netherlands', 'code' => 'NL'),
            array('country_id' => '158', 'tiket_id' => '2', 'negara' => 'New Caledonia', 'code' => 'NC'),
            array('country_id' => '159', 'tiket_id' => '2', 'negara' => 'New Zealand', 'code' => 'NZ'),
            array('country_id' => '160', 'tiket_id' => '2', 'negara' => 'Nicaragua', 'code' => 'NI'),
            array('country_id' => '161', 'tiket_id' => '2', 'negara' => 'Niger', 'code' => 'NE'),
            array('country_id' => '162', 'tiket_id' => '2', 'negara' => 'Nigeria', 'code' => 'NG'),
            array('country_id' => '163', 'tiket_id' => '2', 'negara' => 'Niue', 'code' => 'NU'),
            array('country_id' => '164', 'tiket_id' => '2', 'negara' => 'Norfolk Island', 'code' => 'NF'),
            array('country_id' => '165', 'tiket_id' => '2', 'negara' => 'Northern Mariana Islands', 'code' => 'MP'),
            array('country_id' => '166', 'tiket_id' => '2', 'negara' => 'Norway', 'code' => 'NO'),
            array('country_id' => '167', 'tiket_id' => '2', 'negara' => 'Oman', 'code' => 'OM'),
            array('country_id' => '168', 'tiket_id' => '2', 'negara' => 'Pakistan', 'code' => 'PK'),
            array('country_id' => '169', 'tiket_id' => '2', 'negara' => 'Palau', 'code' => 'PW'),
            array('country_id' => '170', 'tiket_id' => '2', 'negara' => 'Palestine, State of', 'code' => 'PS'),
            array('country_id' => '171', 'tiket_id' => '2', 'negara' => 'Panama', 'code' => 'PA'),
            array('country_id' => '172', 'tiket_id' => '2', 'negara' => 'Papua New Guinea', 'code' => 'PG'),
            array('country_id' => '173', 'tiket_id' => '2', 'negara' => 'Paraguay', 'code' => 'PY'),
            array('country_id' => '174', 'tiket_id' => '2', 'negara' => 'Peru', 'code' => 'PE'),
            array('country_id' => '175', 'tiket_id' => '2', 'negara' => 'Philippines', 'code' => 'PH'),
            array('country_id' => '176', 'tiket_id' => '2', 'negara' => 'Pitcairn', 'code' => 'PN'),
            array('country_id' => '177', 'tiket_id' => '2', 'negara' => 'Poland', 'code' => 'PL'),
            array('country_id' => '178', 'tiket_id' => '2', 'negara' => 'Portugal', 'code' => 'PT'),
            array('country_id' => '179', 'tiket_id' => '2', 'negara' => 'Puerto Rico', 'code' => 'PR'),
            array('country_id' => '180', 'tiket_id' => '2', 'negara' => 'Qatar', 'code' => 'QA'),
            array('country_id' => '181', 'tiket_id' => '2', 'negara' => 'Réunion', 'code' => 'RE'),
            array('country_id' => '182', 'tiket_id' => '2', 'negara' => 'Romania', 'code' => 'RO'),
            array('country_id' => '183', 'tiket_id' => '2', 'negara' => 'Russian Federation', 'code' => 'RU'),
            array('country_id' => '184', 'tiket_id' => '2', 'negara' => 'Rwanda', 'code' => 'RW'),
            array('country_id' => '185', 'tiket_id' => '2', 'negara' => 'Saint Barthélemy', 'code' => 'BL'),
            array('country_id' => '185', 'tiket_id' => '2', 'negara' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH'),
            array('country_id' => '186', 'tiket_id' => '2', 'negara' => 'Saint Kitts and Nevis', 'code' => 'KN'),
            array('country_id' => '187', 'tiket_id' => '2', 'negara' => 'Saint Lucia', 'code' => 'LC'),
            array('country_id' => '188', 'tiket_id' => '2', 'negara' => 'Saint Martin (French part)', 'code' => 'MF'),
            array('country_id' => '189', 'tiket_id' => '2', 'negara' => 'Saint Pierre and Miquelon', 'code' => 'PM'),
            array('country_id' => '190', 'tiket_id' => '2', 'negara' => 'Saint Vincent and the Grenadines', 'code' => 'VC'),
            array('country_id' => '191', 'tiket_id' => '2', 'negara' => 'Samoa', 'code' => 'WS'),
            array('country_id' => '192', 'tiket_id' => '2', 'negara' => 'San Marino', 'code' => 'SM'),
            array('country_id' => '193', 'tiket_id' => '2', 'negara' => 'Sao Tome and Principe', 'code' => 'ST'),
            array('country_id' => '194', 'tiket_id' => '2', 'negara' => 'Saudi Arabia', 'code' => 'SA'),
            array('country_id' => '195', 'tiket_id' => '2', 'negara' => 'Senegal', 'code' => 'SN'),
            array('country_id' => '196', 'tiket_id' => '2', 'negara' => 'Serbia', 'code' => 'RS'),
            array('country_id' => '197', 'tiket_id' => '2', 'negara' => 'Seychelles', 'code' => 'SC'),
            array('country_id' => '198', 'tiket_id' => '2', 'negara' => 'Sierra Leone', 'code' => 'SL'),
            array('country_id' => '199', 'tiket_id' => '2', 'negara' => 'Singapore', 'code' => 'SG'),
            array('country_id' => '200', 'tiket_id' => '2', 'negara' => 'Sint Maarten (Dutch part)', 'code' => 'SX'),
            array('country_id' => '201', 'tiket_id' => '2', 'negara' => 'Slovakia', 'code' => 'SK'),
            array('country_id' => '202', 'tiket_id' => '2', 'negara' => 'Slovenia', 'code' => 'SI'),
            array('country_id' => '203', 'tiket_id' => '2', 'negara' => 'Solomon Islands', 'code' => 'SB'),
            array('country_id' => '204', 'tiket_id' => '2', 'negara' => 'Somalia', 'code' => 'SO'),
            array('country_id' => '205', 'tiket_id' => '2', 'negara' => 'South Africa', 'code' => 'ZA'),
            array('country_id' => '206', 'tiket_id' => '2', 'negara' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'),
            array('country_id' => '207', 'tiket_id' => '2', 'negara' => 'South Sudan', 'code' => 'SS'),
            array('country_id' => '208', 'tiket_id' => '2', 'negara' => 'Spain', 'code' => 'ES'),
            array('country_id' => '209', 'tiket_id' => '2', 'negara' => 'Sri Lanka', 'code' => 'LK'),
            array('country_id' => '210', 'tiket_id' => '2', 'negara' => 'Sudan', 'code' => 'SD'),
            array('country_id' => '211', 'tiket_id' => '2', 'negara' => 'Surinegara', 'code' => 'SR'),
            array('country_id' => '212', 'tiket_id' => '2', 'negara' => 'Svalbard and Jan Mayen', 'code' => 'SJ'),
            array('country_id' => '213', 'tiket_id' => '2', 'negara' => 'Swaziland', 'code' => 'SZ'),
            array('country_id' => '214', 'tiket_id' => '2', 'negara' => 'Sweden', 'code' => 'SE'),
            array('country_id' => '215', 'tiket_id' => '2', 'negara' => 'Switzerland', 'code' => 'CH'),
            array('country_id' => '216', 'tiket_id' => '2', 'negara' => 'Syrian Arab Republic', 'code' => 'SY'),
            array('country_id' => '217', 'tiket_id' => '2', 'negara' => 'Taiwan', 'code' => 'TW'),
            array('country_id' => '218', 'tiket_id' => '2', 'negara' => 'Tajikistan', 'code' => 'TJ'),
            array('country_id' => '219', 'tiket_id' => '2', 'negara' => 'Tanzania, United Republic of', 'code' => 'TZ'),
            array('country_id' => '220', 'tiket_id' => '2', 'negara' => 'Thailand', 'code' => 'TH'),
            array('country_id' => '221', 'tiket_id' => '2', 'negara' => 'Timor-Leste', 'code' => 'TL'),
            array('country_id' => '222', 'tiket_id' => '2', 'negara' => 'Togo', 'code' => 'TG'),
            array('country_id' => '223', 'tiket_id' => '2', 'negara' => 'Tokelau', 'code' => 'TK'),
            array('country_id' => '224', 'tiket_id' => '2', 'negara' => 'Tonga', 'code' => 'TO'),
            array('country_id' => '225', 'tiket_id' => '2', 'negara' => 'Trinidad and Tobago', 'code' => 'TT'),
            array('country_id' => '226', 'tiket_id' => '2', 'negara' => 'Tunisia', 'code' => 'TN'),
            array('country_id' => '227', 'tiket_id' => '2', 'negara' => 'Turkey', 'code' => 'TR'),
            array('country_id' => '228', 'tiket_id' => '2', 'negara' => 'Turkmenistan', 'code' => 'TM'),
            array('country_id' => '229', 'tiket_id' => '2', 'negara' => 'Turks and Caicos Islands', 'code' => 'TC'),
            array('country_id' => '230', 'tiket_id' => '2', 'negara' => 'Tuvalu', 'code' => 'TV'),
            array('country_id' => '231', 'tiket_id' => '2', 'negara' => 'Uganda', 'code' => 'UG'),
            array('country_id' => '232', 'tiket_id' => '2', 'negara' => 'Ukraine', 'code' => 'UA'),
            array('country_id' => '233', 'tiket_id' => '2', 'negara' => 'United Arab Emirates', 'code' => 'AE'),
            array('country_id' => '234', 'tiket_id' => '2', 'negara' => 'United Kingdom', 'code' => 'GB'),
            array('country_id' => '235', 'tiket_id' => '2', 'negara' => 'United States', 'code' => 'US'),
            array('country_id' => '236', 'tiket_id' => '2', 'negara' => 'United States Minor Outlying Islands', 'code' => 'UM'),
            array('country_id' => '237', 'tiket_id' => '2', 'negara' => 'Uruguay', 'code' => 'UY'),
            array('country_id' => '238', 'tiket_id' => '2', 'negara' => 'Uzbekistan', 'code' => 'UZ'),
            array('country_id' => '239', 'tiket_id' => '2', 'negara' => 'Vanuatu', 'code' => 'VU'),
            array('country_id' => '240', 'tiket_id' => '2', 'negara' => 'Venezuela, Bolivarian Republic of', 'code' => 'VE'),
            array('country_id' => '241', 'tiket_id' => '2', 'negara' => 'Viet Nam', 'code' => 'VN'),
            array('country_id' => '242', 'tiket_id' => '2', 'negara' => 'Virgin Islands, British', 'code' => 'VG'),
            array('country_id' => '243', 'tiket_id' => '2', 'negara' => 'Virgin Islands, U.S.', 'code' => 'VI'),
            array('country_id' => '244', 'tiket_id' => '2', 'negara' => 'Wallis and Futuna', 'code' => 'WF'),
            array('country_id' => '245', 'tiket_id' => '2', 'negara' => 'Western Sahara', 'code' => 'EH'),
            array('country_id' => '246', 'tiket_id' => '2', 'negara' => 'Yemen', 'code' => 'YE'),
            array('country_id' => '247', 'tiket_id' => '2', 'negara' => 'Zambia', 'code' => 'ZM'),
            array('country_id' => '248', 'tiket_id' => '2', 'negara' => 'Zimbabwe', 'code' => 'ZW'),
        );
        DB::table('kebangsaans')->insert($countries);
    }
}
